[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/status"
  to = "/status/index.html"
  status = 200

[[headers]]
  for = "/admin/index.html"
  [headers.values]
    Basic-Auth = "admin:asir"

[[headers]]
  for = "/status/index.html"
  [headers.values]
    Basic-Auth = "sysadmin:risa"